-- MySQL Script generated by MySQL Workbench
-- Sun 18 May 2025 12:13:58 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bicosthe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bicosthe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bicosthe` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bicosthe` ;

-- -----------------------------------------------------
-- Table `bicosthe`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicosthe`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicosthe`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicosthe`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `cpf` CHAR(11) NOT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(13) NULL DEFAULT NULL,
  `bloqueado` TINYINT(1) NULL DEFAULT '0',
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicosthe`.`denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicosthe`.`denuncia` (
  `iddenuncia` INT NOT NULL AUTO_INCREMENT,
  `idusuario_denunciado` INT NULL DEFAULT NULL,
  `idusuario_denunciante` INT NULL DEFAULT NULL,
  `motivo` TEXT NULL DEFAULT NULL,
  `data_denuncia` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iddenuncia`),
  INDEX `idusuario_denunciado` (`idusuario_denunciado` ASC) VISIBLE,
  INDEX `idusuario_denunciante` (`idusuario_denunciante` ASC) VISIBLE,
  CONSTRAINT `denuncia_ibfk_1`
    FOREIGN KEY (`idusuario_denunciado`)
    REFERENCES `bicosthe`.`usuario` (`idusuario`),
  CONSTRAINT `denuncia_ibfk_2`
    FOREIGN KEY (`idusuario_denunciante`)
    REFERENCES `bicosthe`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicosthe`.`regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicosthe`.`regiao` (
  `idregiao` INT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `zona` ENUM('Norte', 'Sul', 'Leste', 'Sudeste', 'Centro') NULL DEFAULT NULL,
  PRIMARY KEY (`idregiao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicosthe`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicosthe`.`servico` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `dataInicio` DATETIME NULL DEFAULT NULL,
  `dataFim` DATETIME NULL DEFAULT NULL,
  `idregiao` INT NULL DEFAULT NULL,
  `usuarioId` INT NULL DEFAULT NULL,
  `contato_visivel` TINYINT(1) NULL DEFAULT '0',
  `id_usuario_atribuido` INT NULL DEFAULT NULL,
  `visivel_feed` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`idservico`),
  INDEX `usuarioId` (`usuarioId` ASC) VISIBLE,
  INDEX `id_usuario_atribuido` (`id_usuario_atribuido` ASC) VISIBLE,
  INDEX `idregiao` (`idregiao` ASC) VISIBLE,
  CONSTRAINT `servico_ibfk_1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `bicosthe`.`usuario` (`idusuario`),
  CONSTRAINT `servico_ibfk_2`
    FOREIGN KEY (`id_usuario_atribuido`)
    REFERENCES `bicosthe`.`usuario` (`idusuario`),
  CONSTRAINT `servico_ibfk_3`
    FOREIGN KEY (`idregiao`)
    REFERENCES `bicosthe`.`regiao` (`idregiao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicosthe`.`servico_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicosthe`.`servico_categoria` (
  `idservico` INT NOT NULL,
  `idcategoria` INT NOT NULL,
  PRIMARY KEY (`idservico`, `idcategoria`),
  INDEX `idcategoria` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `servico_categoria_ibfk_1`
    FOREIGN KEY (`idservico`)
    REFERENCES `bicosthe`.`servico` (`idservico`),
  CONSTRAINT `servico_categoria_ibfk_2`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `bicosthe`.`categoria` (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicosthe`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicosthe`.`sessao` (
  `idsessao` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `expira_em` DATETIME NULL DEFAULT NULL,
  `ativo` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`idsessao`),
  INDEX `idusuario` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `sessao_ibfk_1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bicosthe`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bicosthe`.`usuario_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bicosthe`.`usuario_servico` (
  `usuario_idusuario` INT NOT NULL,
  `servico_idservico` INT NOT NULL,
  `data_candidatura` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuario_idusuario`, `servico_idservico`),
  INDEX `servico_idservico` (`servico_idservico` ASC) VISIBLE,
  CONSTRAINT `usuario_servico_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bicosthe`.`usuario` (`idusuario`),
  CONSTRAINT `usuario_servico_ibfk_2`
    FOREIGN KEY (`servico_idservico`)
    REFERENCES `bicosthe`.`servico` (`idservico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
